/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppStudioRouteImport } from './routes/app.studio'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPerfRouteImport } from './routes/app.perf'
import { Route as AppMarketplaceAnalyticsRouteImport } from './routes/app.marketplace-analytics'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppLabsRouteImport } from './routes/app.labs'
import { Route as AppGeneratorRouteImport } from './routes/app.generator'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppDiagramsRouteImport } from './routes/app.diagrams'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppTemplateIdRouteImport } from './routes/app.template.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfRoute = AppPerfRouteImport.update({
  id: '/perf',
  path: '/perf',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceAnalyticsRoute = AppMarketplaceAnalyticsRouteImport.update({
  id: '/marketplace-analytics',
  path: '/marketplace-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagramsRoute = AppDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplateIdRoute = AppTemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/diagrams': typeof AppDiagramsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/generator': typeof AppGeneratorRoute
  '/app/labs': typeof AppLabsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/marketplace-analytics': typeof AppMarketplaceAnalyticsRoute
  '/app/perf': typeof AppPerfRoute
  '/app/profile': typeof AppProfileRoute
  '/app/studio': typeof AppStudioRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/template/$id': typeof AppTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/diagrams': typeof AppDiagramsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/generator': typeof AppGeneratorRoute
  '/app/labs': typeof AppLabsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/marketplace-analytics': typeof AppMarketplaceAnalyticsRoute
  '/app/perf': typeof AppPerfRoute
  '/app/profile': typeof AppProfileRoute
  '/app/studio': typeof AppStudioRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/template/$id': typeof AppTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/diagrams': typeof AppDiagramsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/generator': typeof AppGeneratorRoute
  '/app/labs': typeof AppLabsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/marketplace-analytics': typeof AppMarketplaceAnalyticsRoute
  '/app/perf': typeof AppPerfRoute
  '/app/profile': typeof AppProfileRoute
  '/app/studio': typeof AppStudioRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/template/$id': typeof AppTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/diagrams'
    | '/app/docs'
    | '/app/generator'
    | '/app/labs'
    | '/app/marketplace'
    | '/app/marketplace-analytics'
    | '/app/perf'
    | '/app/profile'
    | '/app/studio'
    | '/app/workspace'
    | '/app/template/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/diagrams'
    | '/app/docs'
    | '/app/generator'
    | '/app/labs'
    | '/app/marketplace'
    | '/app/marketplace-analytics'
    | '/app/perf'
    | '/app/profile'
    | '/app/studio'
    | '/app/workspace'
    | '/app/template/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/diagrams'
    | '/app/docs'
    | '/app/generator'
    | '/app/labs'
    | '/app/marketplace'
    | '/app/marketplace-analytics'
    | '/app/perf'
    | '/app/profile'
    | '/app/studio'
    | '/app/workspace'
    | '/app/template/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/studio': {
      id: '/app/studio'
      path: '/studio'
      fullPath: '/app/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perf': {
      id: '/app/perf'
      path: '/perf'
      fullPath: '/app/perf'
      preLoaderRoute: typeof AppPerfRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace-analytics': {
      id: '/app/marketplace-analytics'
      path: '/marketplace-analytics'
      fullPath: '/app/marketplace-analytics'
      preLoaderRoute: typeof AppMarketplaceAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/labs': {
      id: '/app/labs'
      path: '/labs'
      fullPath: '/app/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generator': {
      id: '/app/generator'
      path: '/generator'
      fullPath: '/app/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagrams': {
      id: '/app/diagrams'
      path: '/diagrams'
      fullPath: '/app/diagrams'
      preLoaderRoute: typeof AppDiagramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/template/$id': {
      id: '/app/template/$id'
      path: '/template/$id'
      fullPath: '/app/template/$id'
      preLoaderRoute: typeof AppTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiagramsRoute: typeof AppDiagramsRoute
  AppDocsRoute: typeof AppDocsRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppLabsRoute: typeof AppLabsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMarketplaceAnalyticsRoute: typeof AppMarketplaceAnalyticsRoute
  AppPerfRoute: typeof AppPerfRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStudioRoute: typeof AppStudioRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppTemplateIdRoute: typeof AppTemplateIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDiagramsRoute: AppDiagramsRoute,
  AppDocsRoute: AppDocsRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppLabsRoute: AppLabsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMarketplaceAnalyticsRoute: AppMarketplaceAnalyticsRoute,
  AppPerfRoute: AppPerfRoute,
  AppProfileRoute: AppProfileRoute,
  AppStudioRoute: AppStudioRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppTemplateIdRoute: AppTemplateIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
